server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: admin-user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/admin/**

        - id: auth-alias
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: dossier-service
          uri: lb://DOSSIER-SERVICE
          predicates:
            - Path=/api/dossiers/**

        - id: document-service
          uri: lb://DOCUMENT-SERVICE
          predicates:
            - Path=/api/documents/**

        - id: workflow-service
          uri: lb://WORKFLOW-SERVICE
          predicates:
            - Path=/api/workflow/**

        - id: paiement-service
          uri: lb://PAIEMENT-SERVICE
          predicates:
            - Path=/api/paiements/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notifications/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-service:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:my-super-secret-key-for-jwt-signing-32chars-min}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
